### ISSUE TITLE
IPv6 addresses not properly handled

### ISSUE THREAD

**Issue by fr3aker** [andryou/scriptsafe#26]
I suspect the problem I described in #4 is/was caused by some improper handling of IPv6 addresses. IPv6 addresses seem completely broken in scriptsafe right now.

When visiting a site that requests JS from a IPv6 address the UI applet breaks with this error:

    Error in event handler for (unknown): Error: Syntax error, unrecognized expression: [rel='x_[false'] [rel='['] .x_[
    at Function.fa.error (chrome-extension://oiigbmnaadbkfbmpbfijlflahbdbdgdf/js/jquery.js:2:12556)
    at fa.tokenize (chrome-extension://oiigbmnaadbkfbmpbfijlflahbdbdgdf/js/jquery.js:2:18609)
    at fa.select (chrome-extension://oiigbmnaadbkfbmpbfijlflahbdbdgdf/js/jquery.js:2:21417)
    at Function.fa [as find] (chrome-extension://oiigbmnaadbkfbmpbfijlflahbdbdgdf/js/jquery.js:2:7143)
    at n.find (chrome-extension://oiigbmnaadbkfbmpbfijlflahbdbdgdf/js/jquery.js:2:23932)
    at n.fn.init (chrome-extension://oiigbmnaadbkfbmpbfijlflahbdbdgdf/js/jquery.js:2:24485)
    at n (chrome-extension://oiigbmnaadbkfbmpbfijlflahbdbdgdf/js/jquery.js:2:405)
    at chrome-extension://oiigbmnaadbkfbmpbfijlflahbdbdgdf/js/popup.js:130:13

Manually adding IPv6 addresses to the whitelist/blacklist is not possible either.  Trying to add the entry `[::1]` to my whitelist shows an `Invalid domain` popup message.

**Comment by andryou** [comment]
Reproduced this bug, I've set up a local server and will test and include a fix for this in the next release. Thank you for the detailed issue.

**Comment by andryou** [comment]
Please try v1.0.7.8 and close this issue if resolved, thanks!

**Comment by andryou** [comment]
(sorry for the delay in getting v1.0.7.8 to you; it's been "Pending Review" in the Chrome Web Store since I pushed it out 8:45pm eastern yesterday)

**Comment by andryou** [comment]
I've been refreshing the Developer Dashboard all day to check on the status and I'm happy to announce v1.0.7.8 has been published on the Chrome Web Store within the past half hour.

**Comment by fr3aker** [comment]
Works like a charm, thanks for the fast fix!
